export const ADDRESS_CREATE_REQUEST = "ADDRESS_CREATE_REQUEST"
export const ADDRESS_CREATE_SUCCESS = "ADDRESS_CREATE_SUCCESS"
export const ADDRESS_CREATE_FAIL = "ADDRESS_CREATE_FAIL"

export const ADDRESS_LIST_MY_REQUEST = "ADDRESS_LIST_MY_REQUEST"
export const ADDRESS_LIST_MY_SUCCESS = "ADDRESS_LIST_MY_SUCCESS"
export const ADDRESS_LIST_MY_FAIL = "ADDRESS_LIST_MY_FAIL"
export const ADDRESS_LIST_MY_RESET = "ADDRESS_LIST_MY_RESET"
